version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talentflow-web
    command: sh -c "npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
